### ISSUE TITLE
Research for Complaint Manager v2.0

### ISSUE THREAD

**Issue by justin-c-anthony** [Impactworkers/iw-complaint-manager#8]
This is a card to track all the research for Complaint Manager v2.0. 

Track overall progress here: https://github.com/PublicDataWorks/complaint-manager/milestone/24

Product
- [ ] Look into other Digital Public Goods that have similar use cases, see how they are configured, distributed and documented. If needed get a dev to clone it and do further investigation. #493 

Design
- [x] Figure out if we can use a MUI Templates to speed up delivery #486 (tl;dr we can't as they will not allow us to distribute souce code)
- [x] Decide if we go with Tailwind or SASS with MUI for v2.0 #502
- [x] Feedback from Public Data Works
- [x] Feedback from Hawaii (Cara + Geroge)
- [x] Feedback from Hawaii (Christin)
- [x] Feedback from NOIPM 

Tech
- [x] Determine if there are open-source Content Management Systems (CMS) in the market that allow us to customize fields and can be something for us to use the the future @justin-c-anthony (to add details on open source tool that works)
- [x] Determine if we can use business/rules as code tools (BPNM Engine like Camunda) for v2.0 - done by @faraakhatTW (current inconclusive and need more research)
- [x] Verify existing costs to maintain system so our current and future users can be aware of maintenance costs #503 
- [x] Organize meetings to discuss ways to improve backend for v2.0 and tech best practices meeting to prep team for v2.0 #490  @heliofreitastw @faraakhatTW
- [x] Research Vite/React Vite @justin-c-anthony 
- [ ] Research Redux Toolkit (RTK) @justin-c-anthony 
- [x] Research NestJS #520 

Testing
- [x] Figure out the best testing framework to use for v2.0 #347 @thoughtworks-vwong 
- [ ] Write automated regression tests in Cyprus @thoughtworks-vwong 

Documentation
- [x] Figure out best practices and migrate current documentation to something that meets Digital Public Goods standards #499 @mariahsager-tw
- [x] Figure out the correct github repo for v2.0 @sbhamani 

Staffing
- [x] Draft what we need for senior dev/SME support to list in beach job jar

Meetings
- [x] Refinement: MVP overview 1: https://drive.google.com/file/d/1J1D256MnEtqwlZcg-Rochd1WCPaBznIz/view?usp=drive_link
- [x] Refinement: MVP overview 2
- [x] [Devs] MVP Tech Discussion

**Comment by justin-c-anthony** [comment]
Copied from Reshmi:

We put in request for beach support:

Scope: Pair with TL (@Shakeel Bhamani ) and devs on the Hawaii CSOC project on back-end setup and best practices (i.e. API framework, CI pipeline, docker setup, other infra setup)

Tech stack
TypeScript (or just JavaScript)
React
Node
PostgreSQL (any relational database experience)
Circle CI
AWS (nice-to-have)

Skills
Experience in API and database best practices
Experience in CI/CD best practices (basically someone good at setting up an app from scratch using best practices but doesn’t need to worry about the front-end)

Preferred
Seniority: Senior or above
Timeline: 2 weeks or more
